apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: processor-rb
  namespace: data-processor
subjects:
- kind: ServiceAccount
  name: processor-sa
  namespace: data-processor
roleRef:
  kind: Role
  name: processor-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
  namespace: data-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      serviceAccountName: processor-sa
      containers:
      - name: ubi
        image: registry.redhat.io/ubi8/ubi:latest
        command: ["sleep", "infinity"]
        envFrom:
        - configMapRef:
            name: processor-config
        - configMapRef:
            name: db-config
