apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: nginx
        image: image: registry.redhat.io/ubi8/nginx-120:latest
        volumeMounts:
        - name: html
          mountPath: /opt/app-root/src
        ports:
        - containerPort: 8080
      volumes:
      - name: html
        configMap:
          name: hello-config
