apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-restrict-tag-placement
  namespace: acm-policies
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - <enter managedclusterset name>
