apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-restrict-tag-placement
  namespace: acm-policies
placementRef:
  name: policy-restrict-tag-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-restrict-tag
    apiGroup: policy.open-cluster-management.io
    kind: Policy

