apiVersion: v1
kind: ConfigMap
metadata:
  name: node-api-config
  namespace: node-api
data:
  server.js: |
    const express = require('express');
    const app = express();
    const PORT = process.env.PORT || 3000;
    app.get('/', (req, res) => {
      res.send('Hello from Node.js API on ACM GitOps!');
    });
    app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
