apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: log-hpa
  namespace: log-viewer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
